### PR TITLE
Add docs, examples

### PR DESCRIPTION
**Pull request by 0x1eef**

### CODE REVIEW

**Comment by antaz** [comment]
This looks nice

**Comment by 0x1eef** [comment]
@antaz 
I added tests [here](https://github.com/antaz/llm/pull/36/commits/0af8461b9f543ff41825bcf68bf36bb10483e10a) that cover the README examples. For now I only covered the lazy conversation example. Since the conversation example makes multiple requests that seemed a bit trickier to mock

**Comment by antaz** [comment]
> @antaz I added tests ~[here](https://github.com/antaz/llm/pull/36/commits/0af8461b9f543ff41825bcf68bf36bb10483e10a)~ [here](https://github.com/antaz/llm/pull/36/commits/403f0bc313992709f65e41250d7bf12a88e1d3e4) that cover the README examples. For now I only covered the lazy conversation example. Since the conversation example makes multiple requests that seemed a bit trickier to mock

@0x1eef shouldn't we just test `#chat` and `#chat!` ? that would be sufficient to cover the readme example

**Comment by 0x1eef** [comment]
> shouldn't we just test #chat and #chat! ? 

This approach does test `#chat!` and at the same time it tests the `README.md` example as-it-is as well. This approach is more like an integration test, and it is testing our documentation. What don't you like about this approach ?

**Pull request merged**
